# Generated by Django 5.0.6 on 2024-07-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_test_testanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testanswer',
            old_name='answer_id',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='testanswer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='testanswer',
            old_name='test_id',
            new_name='test',
        ),
    ]
